server:
  # 端口
  port: 8080
  undertow:
    # 编码
    uri-encoding: UTF-8
spring:
  main:
    allow-bean-definition-overriding: true
  resources:
    # 静态资源文件夹
    static-locations: classpath:/mapper/*.xml
  # 序列化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      #忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    #设置空如何序列化
    defaultPropertyInclusion: ALWAYS
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true

# 分库
sharding:
  jdbc:
    datasource:
      names: gd,hn
      gd:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://172.16.0.35:3306/dms?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
      hn:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://172.16.0.36:3306/dms?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
    config:
      sharding:
        # 默认数据源（未设置分表策略的表将默认用此数据源）
        default-datasource-name: gd
        # 默认分库策略
        default-database-strategy:
          inline:
            sharding-column: area_code
            # 自定义的分片策略
            algorithm-expression: $->{area_code}
        # 分表策略
        tables:
          # 分库分表
          biz_user_quote_info:
            actual-data-nodes: ${['hn','gd']}.biz_user_quote_info_$->{202005..202008}
            # 精确分片算法，对应PreciseShardingAlgorithm
            table-strategy:
              inline:
                sharding-column: scopde_date
                # 自定义的分片策略
                algorithm-expression: $->{scope_date.substring(0,7)}
            # 范围分片算法，对应RangeShardingAlgorithm，略
            # 复合分片算法，对应ComplexKeysShardingAlgorithm，略
        props:
          sql:
            show: true

# mybatis-plus
mybatis-plus:
  mapper-locations: /mapper/**/**.xml
  typeAliasesPackage: com.dms.clout.entity
  global-config:
    id-type: 3
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl