package com.gx.common.CollectionTemplate;

public class StringAndStringBuilder {

    public static void main(String[] args) {
        long time = System.currentTimeMillis();
        String str = null;
        Integer i = 0;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        str = str + i;
        long time2 = System.currentTimeMillis();
        System.out.println(time2 - time);
        System.out.println(str);

        long time3 = System.currentTimeMillis();
        StringBuilder sb = new StringBuilder();

        StringBuffer sf = new StringBuffer();

        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        sb.append(i);
        long time4 = System.currentTimeMillis();
        System.out.println(time4 - time3);
        System.out.println(sb.toString());


    }

}
