server:
  port: 8080

spring:
  redis:
    host: 172.16.0.36
    database: 0
  datasource:
    url: jdbc:mysql://172.16.0.35:3306/dms?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver