server:
  # 端口
  port: 8080
  undertow:
    # 编码
    uri-encoding: UTF-8
spring:
  main:
    allow-bean-definition-overriding: true
  resources:
    # 静态资源文件夹
    static-locations: classpath:/mapper/*.xml
  # 序列化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      #忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    #设置空如何序列化
    defaultPropertyInclusion: ALWAYS
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
  aop:
    proxy-target-class: true
    auto: true
  # 分库
  datasource:
    gdel:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.16.0.35:3306/dms?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
    gdfm:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.16.0.35:3306/dms_fm?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
    gdpr:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.16.0.35:3306/dms_pr?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root

# mybatis-plus
mybatis-plus:
  mapper-locations: /mapper/**/**.xml
  typeAliasesPackage: com.dms.cloud.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl